default: &default
  adapter: postgresql
  encoding: unicode
pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: testblog_development
test:
  <<: *default
  database: testblog_test

production:
  <<: *default
  database: testblog_production
  username: testblog
  password: <%= ENV['TESTBLOG_DATABASE_PASSWORD'] %>
